### ISSUE TITLE
Is it possible to use unleashed view from kaban view ?

### ISSUE THREAD

**Issue by njeudy** [trobz/openerp-web-unleashed#3]
I want to create a simple unleashed made view :) for project.project model.

I want to use kaban view from openERP and when clicking on it fire my new view ? I only need to use action for this ?

Can you give me a working example if possible ?

**Comment by zazabe** [comment]
Hi, 

I think it's easier to put a web unleashed view in existing openerp views than the opposite but i don't have so much experience for now...

Unleashed view are Marionette view at the end, and you can easily do a `new FooView()` somewhere, but on the other side, doing a `new NativeOpenERPView()` seems much more harder, because OpenERP views are instantiated in a very specific context and have lot of dependencies on the OpenERP ViewManager...

Has for ticket #1, it's something we are working on, so some update should be available soon on this ;)
